### ISSUE TITLE
unet pipeline stopped, and can't restart.

### ISSUE THREAD

**Issue by mscafferty** [neptune-ml/data-science-bowl-2018#53] opened 2018-03-16 01:31 UTC
Hi, I started with the command:

neptune send main.py --worker gcp-gpu-medium --config neptune.yaml --environment pytorch-0.2.0-gpu-py3 -- train_evaluate_predict_pipeline --pipeline_name unet

and the process ran on the cloud for about two days, ending with what looked like training completed, but stopped soon after without predicting:
 
--
134006.617694 | 2018-03-15 15-18-13 steps >>> training finished
134140.875169 | 2018-03-15 15-20-27 steps >>> step unet saving transformer...
134141.531521 | 2018-03-15 15-20-28 steps >>> step unet caching outputs...
134142.929724 | 2018-03-15 15-20-29 steps >>> step unet saving outputs...
134144.348572 | 2018-03-15 15-20-31 steps >>> step mask_resize adapting inputs
134144.348928 | 2018-03-15 15-20-31 steps >>> step mask_resize fitting and transforming...
134147.812994 | 2018-03-15 15-20-34 steps >>> step mask_resize saving transformer...
134147.813879 | 2018-03-15 15-20-34 steps >>> step mask_resize caching outputs...
134149.567436 | 2018-03-15 15-20-36 steps >>> step mask_resize saving outputs...
134151.522851 | 2018-03-15 15-20-38 steps >>> step mask_thresholding adapting inputs
134151.52318 | 2018-03-15 15-20-38 steps >>> step mask_thresholding fitting and transforming...
134151.672155 | 2018-03-15 15-20-38 steps >>> step mask_thresholding saving transformer...
134151.82704 | 2018-03-15 15-20-38 steps >>> step mask_thresholding caching outputs...
134152.389651 | 2018-03-15 15-20-39 steps >>> step mask_thresholding saving outputs...
134152.690208 | 2018-03-15 15-20-39 steps >>> step labeler adapting inputs
134152.6905 | 2018-03-15 15-20-39 steps >>> step labeler fitting and transforming...
134153.141942 | 2018-03-15 15-20-40 steps >>> step labeler saving transformer...
134153.290386 | 2018-03-15 15-20-40 steps >>> step labeler caching outputs...
134154.242258 | 2018-03-15 15-20-41 steps >>> step labeler saving outputs...
134155.191069 | 2018-03-15 15-20-42 steps >>> step output adapting inputs
134155.633434 | Sentry is attempting to send 1 pending error messages
134155.633786 | Waiting up to 10 seconds
134155.63392 | Press Ctrl-C to quit

with the error messages:

134147.813554 | 0it  [00:00, ?it/s] 16it [00:00, 151.25it/s] 33it [00:00, 152.86it/s] 52it  [00:00, 162.17it/s] 64it [00:00, 121.54it/s] 79it [00:00,  125.23it/s] 99it [00:00, 139.29it/s] 113it [00:00, 133.18it/s] 129it  [00:00, 136.78it/s] 145it [00:01, 141.44it/s] 160it [00:01,  124.15it/s] 177it [00:01, 134.14it/s] 192it [00:01, 137.08it/s] 210it  [00:01, 147.14it/s] 232it [00:01, 154.38it/s] 248it [00:01,  141.08it/s] 263it [00:01, 128.33it/s] 279it [00:02, 125.77it/s] 294it  [00:02, 127.98it/s] 314it [00:02, 143.28it/s] 334it [00:02,  155.25it/s] 351it [00:02, 156.51it/s] 368it [00:02, 158.29it/s] 385it  [00:02, 143.10it/s] 406it [00:02, 157.98it/s] 425it [00:02,  165.58it/s] 443it [00:03, 165.30it/s] 461it [00:03, 168.39it/s] 486it  [00:03, 183.31it/s] 509it [00:03, 191.29it/s] 531it [00:03, 155.82it/s]
-- | --
134155.454488 | Traceback (most recent call last):
134155.454765 | File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
134155.454923 | execute()
134155.455073 | File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
134155.455227 | execfile(job_filepath, job_globals)
134155.455392 | File "/usr/local/lib/python3.6/dist-packages/past/builtins/misc.py", line 82, in execfile
134155.455511 | exec_(code, myglobals, mylocals)
134155.455667 | File "main.py", line 181, in <module>
134155.455816 | action()
134155.455973 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
134155.456105 | return self.main(*args, **kwargs)
134155.456236 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
134155.45638 | rv = self.invoke(ctx)
134155.456507 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
134155.456749 | return _process_result(sub_ctx.command.invoke(sub_ctx))
134155.456909 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
134155.457037 | return ctx.invoke(self.callback, **ctx.params)
134155.457165 | File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
134155.457291 | return callback(*args, **kwargs)
134155.457419 | File "main.py", line 153, in train_evaluate_predict_pipeline
134155.457555 | _train_pipeline(pipeline_name, validation_size)
134155.457738 | File "main.py", line 80, in _train_pipeline
134155.457877 | pipeline.fit_transform(data)
134155.458006 | File "/neptune/steps/base.py", line 95, in fit_transform
134155.458134 | step_inputs = self.adapt(step_inputs)
134155.458262 | File "/neptune/steps/base.py", line 181, in adapt
134155.458392 | raw_inputs = [step_inputs[step_name][step_var] for step_name, step_var in step_mapping]
134155.458521 | File "/neptune/steps/base.py", line 181, in <listcomp>
134155.45866 | raw_inputs = [step_inputs[step_name][step_var] for step_name, step_var in step_mapping]
134155.45879 | KeyError: 'labels'

I tried to restart by setting overwrite: 0 in neptune.yaml and using the command:

neptune run main.py -- train_evaluate_predict_pipeline --pipeline_name unet

but got the error:

9.559113 | Traceback (most recent call last):
-- | --
9.559424 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
9.559623 | execute()
9.559817 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
9.560009 | execfile(job_filepath, job_globals)
9.560202 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/past/builtins/misc.py", line 82, in execfile
9.560394 | exec_(code, myglobals, mylocals)
9.560585 | File "main.py", line 181, in <module>
9.560775 | action()
9.560967 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/click/core.py", line 722, in __call__
9.561159 | return self.main(*args, **kwargs)
9.56135 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/click/core.py", line 697, in main
9.56154 | rv = self.invoke(ctx)
9.56173 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
9.56193 | return _process_result(sub_ctx.command.invoke(sub_ctx))
9.562121 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/click/core.py", line 895, in invoke
9.562311 | return ctx.invoke(self.callback, **ctx.params)
9.562502 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/click/core.py", line 535, in invoke
9.562691 | return callback(*args, **kwargs)
9.562883 | File "main.py", line 153, in train_evaluate_predict_pipeline
9.563096 | _train_pipeline(pipeline_name, validation_size)
9.563288 | File "main.py", line 66, in _train_pipeline
9.563479 | meta = pd.read_csv(os.path.join(params.meta_dir, 'stage1_metadata.csv'))
9.563672 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/pandas/io/parsers.py", line 709, in parser_f
9.563862 | return _read(filepath_or_buffer, kwds)
9.564052 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/pandas/io/parsers.py", line 449, in _read
9.564242 | parser = TextFileReader(filepath_or_buffer, **kwds)
9.564436 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/pandas/io/parsers.py", line 818, in __init__
9.564625 | self._make_engine(self.engine)
9.564815 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
9.565005 | self._engine = CParserWrapper(self.f, **self.options)
9.565195 | File "/home/michael/.virtualenvs/unet-pytorch/lib/python3.5/site-packages/pandas/io/parsers.py", line 1695, in __init__
9.565386 | self._reader = parsers.TextReader(src, **kwds)
9.56558 | File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
9.565773 | File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
9.565963 | FileNotFoundError: File b'/public/dsb_2018_data/stage1_metadata.csv' does not exist

 I  appreciate any advice you may have.

**Comment by jakubczakon** [comment] 2018-03-19 09:28
@mscafferty there was a bug on master with the names in the `unet` pipeline and since we were working only on `unet_multitask` and other stuff we didn't spot it before. It is fixed now.

When it comes to what to do now. You pipeline fitted all the heavy blocks like `unet` transformer and saved them so we don't want to loose that. You can approach it in 3 ways:

* download transformers from `/output/your_experiment_name` and run it locally while setting 
```yaml
overwrite: 0
```
in the `neptune.yaml` . It will fit only what is missing (in this case only the dummy transformer called 'output'). You can also just create a file called 'output' in the transformers directory and run `neptune run --- evaluate_predict_pipeline -p unet` and it will work as well but I don't recommend dirty tricks like that.

* second option is having downloaded the pipeline you can upload it to neptune via `neptune data upload my_data` command. It will be pushed to `/input/` directory. Now this directory is read only so if you want to reuse this data I would suggest that you go ahead and create a snippet that copies this `experiment_dir` directory (containing `transformers`) that you uploaded to the `/output/` folder and then run you experiment normally. So just have something like 
```python
import subprocess
subprocess.call('cp -rf /input/my_experiment /output`, shell=True)
```
at the top of your `main.py`. remember to have this filepath defined in the `neptune.yaml` config file.

* third option is to upload both epxeriment_dir and the whole project code to neptune and rerun it in notebook by using bash cells. Meaning:
`! cp /input/my_experiments /output`
`! neptune run 'train_evaluate_predict_pipeline -p unet` 

When retraining remember to set `overwrite: 0` so that you would keep your previously fitted transformers.

**Comment by kamil-kaczmarek** [comment] 2018-03-21 17:00
Hi @mscafferty, 

1. @jakubczakon covered your first error very well.
2. Your second error is caused by incorrect directories. When doing: `neptune run main.py -- train_evaluate_predict_pipeline --pipeline_name unet_multitask` make sure that you put correct parameters in the [neptune.yaml](https://github.com/neptune-ml/data-science-bowl-2018/blob/master/neptune.yaml#L25):
* comment _Cloud Environment_ block
* uncomment _Local Environment_ block and put dirs there

If you need metadata or masks run this:
```bash
neptune run main.py -- prepare_metadata
neptune run main.py -- prepare_masks
```

Best,
Kamil

**Comment by kamil-kaczmarek** [comment] 2018-03-27 05:57
closing this.

**Closed by kamil-kaczmarek** 2018-03-27 05:57 UTC
