### ISSUE TITLE
Problem with post processing

### ISSUE THREAD

**Issue by etheleon** [neptune-ml/data-science-bowl-2018#47] opened 2018-03-13 14:47 UTC
Hi, i'm running unet_multitask

ended training at epoch 256
errored out when doing post processing. 

```
2018-03-13 09-52-02 steps >>> step detached fitting and transforming...
228it [02:11,  1.14it/s]Traceback (most recent call last):
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
    execute()
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
    execfile(job_filepath, job_globals)
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/past/builtins/misc.py", line 82, in execfile
    exec_(code, myglobals, mylocals)
  File "main.py", line 181, in <module>
    action()
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/uesu/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 153, in train_evaluate_predict_pipeline
    _train_pipeline(pipeline_name, validation_size)
  File "main.py", line 80, in _train_pipeline
    pipeline.fit_transform(data)
  File "/data/neptune/data-science-bowl-2018/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/data/neptune/data-science-bowl-2018/steps/base.py", line 98, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/data/neptune/data-science-bowl-2018/steps/base.py", line 109, in _cached_fit_transform
    step_output_data = self.transformer.fit_transform(**step_inputs)
  File "/data/neptune/data-science-bowl-2018/steps/base.py", line 242, in fit_transform
    return self.transform(*args, **kwargs)
  File "/data/neptune/data-science-bowl-2018/postprocessing.py", line 134, in transform
    labeled_image = postprocess(image, contour)
  File "/data/neptune/data-science-bowl-2018/postprocessing.py", line 170, in postprocess
    cleaned_mask = clean_mask(image, contour)
  File "/data/neptune/data-science-bowl-2018/postprocessing.py", line 221, in clean_mask
    m_ = np.where(c_b & (~m_b), 0, m_)
ValueError: operands could not be broadcast together with shapes (512,640) () (516,644)
```

**Comment by jakubczakon** [comment] 2018-03-13 16:04
Hi,
Since all the transformers are trained and saved no work is lost thankfully.
This error is already fixed on master but you might have gotten the earler version.
It comes from the pad and crop functions that before had == instead of <= as you can see here:

```python
def pad_mask(mask, pad):
    if pad <= 1:
        pad = 2
    h, w = mask.shape
    h_pad = h + 2 * pad
    w_pad = w + 2 * pad
    mask_padded = np.zeros((h_pad, w_pad))
    mask_padded[pad:pad + h, pad:pad + w] = mask
    mask_padded[pad - 1, :] = 1
    mask_padded[pad + h + 1, :] = 1
    mask_padded[:, pad - 1] = 1
    mask_padded[:, pad + w + 1] = 1

    return mask_padded


def crop_mask(mask, crop):
    if crop <= 1:
        crop = 2
    h, w = mask.shape
    mask_cropped = mask[crop:h - crop, crop:w - crop]
    return mask_cropped
```
The best way forward now is to change that in the code (or get master) change `overwrite=0` in `nepune.yaml` and run train_evaluate_predict.py again. It will only train the postprocessing transformer and the rest will be kept as is. You can copy what you trained somewhere else for backup just in case.

**Comment by etheleon** [comment] 2018-03-14 10:36
hi when you say run  train_evaluate_predict.py again you mean to say 

`neptune run main.py -- train_evaluate_predict_pipeline --pipeline_name unet_multitask` ?

**Comment by jakubczakon** [comment] 2018-03-14 11:38
exactly but remember to set this `overwrite: 0` in `neptune.yaml`

**Comment by etheleon** [comment] 2018-03-15 10:42
Yea i did that. Thanks for the tip. However, the submitted LB was 0.39. 

It stopped at epoch 256, I understand the patience was step to 100. maybe try with smaller learning rate and smaller batch?

I'm going to rerun

**Comment by jakubczakon** [comment] 2018-03-15 10:50
I will look into that.

Also unfortunately the training is not seeded as of yet which will be changed in the next version so we would have it fully reproducible. 
However such a large gap is alarming. I would expect something like 0.415+ at the very minimum.

There are lots of hyperparams that you can try changing and that is exactly what I would love the users of this code to do. Everything is available in the  `neptune.yaml` file.
One really cool thing is that by setting given parameter to say:

```yaml
 lr:
    value: [0.01,0.005,0.002,0.001]
```
Neptune will run 4 experiments with those parameters and you can compare all of them in the dashboards.

**Comment by etheleon** [comment] 2018-03-15 11:04
that's very cool!!

**Closed** 2018-03-21 16:37 UTC
